# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: docker hub login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: build docker image
          command: |
            docker build -t cuongtructran/py-cloudflare-ddns:$CIRCLE_BRANCH .
      - run:
          name: push docker image
          command: |
            docker push cuongtructran/py-cloudflare-ddns:$CIRCLE_BRANCH
workflows:
  version: 2
  psuh-to-dockerhub:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/