# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-branch:
    machine: true
    steps:
      - checkout
      - run:
        name: docker hub login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: build docker image
          command: |
            docker build -t cuongtructran/py-cloudflare-ddns:$CIRCLE_BRANCH .
      - run:
          name: push docker image
          command: |
            docker push cuongtructran/py-cloudflare-ddns:$CIRCLE_BRANCH
  build-tag:
    machine: true
    steps:
      - checkout
      - run:
          name: docker hub login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: build docker image
          command: |
            docker build -t cuongtructran/py-cloudflare-ddns:$CIRCLE_TAG .
      - run:
          name: push docker image
          command: |
            docker push cuongtructran/py-cloudflare-ddns:$CIRCLE_TAG
workflows:
  version: 2
  push-to-dockerhub:
    jobs:
      - build-branch:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
      - build-tag:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/